### ISSUE TITLE
Rubocop engine build failed

### ISSUE THREAD

**Issue by BernardoMG** [codeclimate/codeclimate-rubocop#131]
I'm trying to add `codeclimate.yml` but I'm having problems with rubocop engine.

This is my `codeclimate.yml`:

````yml
version: 2 # required to adjust maintainability checks

checks:
  argument-count:
    enabled: true

complex-logic:
  enabled: true

file-lines:
  enabled: true

identical-code:
  enabled: true

method-complexity:
  enabled: true

method-count:
  enabled: true

method-lines:
  enabled: true

nested-control-flow:
  enabled: true

return-statements:
  enabled: true

similar-code:
  enabled: true

exclude_patterns:
 - "config/"
 - "db/"
 - "**/node_modules/"
 - "**/vendor/"
 - "**/*_test.go"
 - "**/*.d.ts"

plugins:
  brakeman:
    enabled: true

  csslint:
    enabled: true

  eslint:
    enabled: true
    config:
      config: .eslintrc

  reek:
    enabled: true

  rubocop:
    enabled: true
    config:
      file: .rubocop.yml

  scss-lint:
    enabled: true

````

And this is my rubocop.yml:

````yml
require: rubocop-airbnb

inherit_from: .rubocop_airbnb.yml
````

I have installed rubocop-airbnb gem ([Source](https://github.com/airbnb/ruby/tree/master/rubocop-airbnb)) and its declared on my Gemfile.

Running `codeclimage analyze` gives the following output:

````sh
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:122:in `require': cannot load such file -- rubocop-airbnb (LoadError)
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:122:in `require'
	from /usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/config_loader_resolver.rb:15:in `block in resolve_requires'
	from /usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/config_loader_resolver.rb:11:in `each'
	from /usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/config_loader_resolver.rb:11:in `resolve_requires'
	from /usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/config_loader.rb:38:in `load_file'
	from /usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/config_store.rb:23:in `options_config='
	from /usr/src/app/lib/cc/engine/rubocop.rb:55:in `block in config_store'
	from /usr/src/app/lib/cc/engine/rubocop.rb:53:in `tap'
	from /usr/src/app/lib/cc/engine/rubocop.rb:53:in `config_store'
	from /usr/src/app/lib/cc/engine/rubocop.rb:46:in `files_to_inspect'
	from /usr/src/app/lib/cc/engine/rubocop.rb:29:in `block in run'
	from /usr/src/app/lib/cc/engine/rubocop.rb:28:in `chdir'
	from /usr/src/app/lib/cc/engine/rubocop.rb:28:in `run'
	from /usr/src/app/bin/codeclimate-rubocop:17:in `<main>'
````

Any ideas about this?
