### ISSUE TITLE
channel rubocop-0-60 does not run rubocop. 

### ISSUE THREAD

**Issue by raykin** [codeclimate/codeclimate-rubocop#142]
My config is 
```yml
version: 2
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-60
```
but the rubocop doesn't run at all. The build page shows the step of rubocop only take 2 seconds but no error. If I use the default 0.52 rubocop, it becomes workable and take 1 minute.

How can I debug this weird case?
