### ISSUE TITLE
Version 0.76 is released

### ISSUE THREAD

**Issue by Mange** [codeclimate/codeclimate-rubocop#210]
I do hope #93 could get implemented some day, but until then, here's yet another reminder issue of a new Rubocop version. :smile:

**Comment by bestwebua** [comment]
Hello! When I plug new rubocop version in .codeclimate.yml
```yml
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-76
```
codeclimate ignores my rubocop configuration from ```.rubocop.yml``` and runs rubocop with default config. How to fix this behaviour? Thanks!
