### ISSUE TITLE
Version 0.78 is released

### ISSUE THREAD

**Issue by stefanahman** [codeclimate/codeclimate-rubocop#216]
Version 0.78 is released! 🎉

**Comment by davehenton** [comment]
Rubocop 0.78 (as well as Rubocop 0.79) is now available in Code Climate. To use this newer version, you'll need to commit a .codeclimate.yml with the following configuration:

```
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-78
```
