### ISSUE TITLE
Version 0.79 is released

### ISSUE THREAD

**Issue by stefanahman** [codeclimate/codeclimate-rubocop#219]
Please upgrade the `codeclimate-rubocop` version...

**Comment by stefanahman** [comment]
@filipesperandio 🙏

**Comment by davehenton** [comment]
Hi @stefanahman , sorry for the delay here! 

Rubocop 0.79 is now available in Code Climate. To use this newer version, you'll need to commit a .codeclimate.yml with the following configuration:

```
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-79
```
