### ISSUE TITLE
Version 0.80 is released

### ISSUE THREAD

**Issue by stefanahman** [codeclimate/codeclimate-rubocop#223]
New rubocop version Mr @davehenton 🙏 
https://github.com/rubocop-hq/rubocop/releases/tag/v0.80.0

**Comment by davehenton** [comment]
@stefanahman 

Rubocop 0.80 is now available in Code Climate. To use this newer version, you'll need to commit a .codeclimate.yml with the following configuration:

```
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-80
```
