### ISSUE TITLE
undefined method `on_numblock' for RuboCop::Cop::Commissioner

### ISSUE THREAD

**Issue by stefanahman** [codeclimate/codeclimate-rubocop#224]
```yaml
# .codeclimate.yml
version: "2"
checks:
  file-lines:
    enabled: false
  method-lines:
    enabled: false
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
      - javascript:
    exclude_patterns:
    - test/
  rubocop:
    enabled: true
    channel: rubocop-0-79
exclude_patterns:
- config/
- db/
- vendor/
```

Error on CodeClimate:

![image](https://user-images.githubusercontent.com/1053201/74805374-2b8df980-52e3-11ea-8d16-1a0ee28892a8.png)

```ruby
/usr/local/bundle/gems/rubocop-0.79.0/lib/rubocop/ast/traversal.rb:114:in `block in on_send': undefined method `on_numblock' for #<RuboCop::Cop::Commissioner:0x00005595af1db600> (NoMethodError)
Did you mean?  on_block
	from /usr/local/bundle/gems/rubocop-0.79.0/lib/rubocop/ast/traversal.rb:111:in `each'
	from /usr/local/bundle/gems/rubocop-0.79.0/lib/rubocop/ast/traversal.rb:111:in `each_with_index'
	from /usr/local/bundle/gems/rubocop-0.79.0/lib/rubocop/ast/traversal.rb:111:in `on_send'
	from /usr/local/bundle/gems/rubocop-0.79.0/lib/rubocop/cop/commissioner.rb:33:in `block (2 levels) in <class:Commissioner>'
	from /usr/local/bundle/gems/rubocop-0.79.0/lib/rubocop/ast/traversal.rb:114:in `block in on_send'
	from /usr/local/bundle/gems/rubocop-0.79.0/lib/rubocop/ast/traversal.rb:111:in `each'
	from /usr/local/bundle/gems/rubocop-0.79.0/lib/rubocop/ast/traversal.rb:111:in `each_with_index'
	from /usr/local/bundle/gems/rubocop-0.79.0/lib/rubocop/ast/traversal.rb:111:in `on_send'
	from /usr/local/bundle/gems/rubocop-0.79.0/lib/rubocop/cop/commissioner.rb:33:in `block (2 levels) in <class:Commissioner>'
	from /usr/local/bundle/gems/rubocop-0.79.0/lib/rubocop/ast/traversal.rb:57:in `block in on_begin'
	from /usr/local/bundle/gems/rubocop-0.79.0/lib/rubocop/ast/traversal.rb:57:in `each'
	from /usr/local/bundle/gems/rubocop-0.79.0/lib/rubocop/ast/traversal.rb:57:in `on_begin'
	from /usr/local/bundle/gems/rubocop-0.79.0/lib/rubocop/cop/commissioner.rb:33:in `block (2 levels) in <class:Commissioner>'
	from /usr/local/bundle/gems/rubocop-0.79.0/lib/rubocop/ast/traversal.rb:107:in `on_def'
	from /usr/local/bundle/gems/rubocop-0.79.0/lib/rubocop/cop/commissioner.rb:33:in `block (2 levels) in <class:Commissioner>'
	from /usr/local/bundle/gems/rubocop-0.79.0/lib/rubocop/ast/traversal.rb:57:in `block in on_begin'
	from /usr/local/bundle/gems/rubocop-0.79.0/lib/rubocop/ast/traversal.rb:57:in `each'
	from /usr/local/bundle/gems/rubocop-0.79.0/lib/rubocop/ast/traversal.rb:57:in `on_begin'
	from /usr/local/bundle/gems/rubocop-0.79.0/lib/rubocop/cop/commissioner.rb:33:in `block (2 levels) in <class:Commissioner>'
	from /usr/local/bundle/gems/rubocop-0.79.0/lib/rubocop/ast/traversal.rb:99:in `on_class'
	from /usr/local/bundle/gems/rubocop-0.79.0/lib/rubocop/cop/commissioner.rb:33:in `block (2 levels) in <class:Commissioner>'
	from /usr/local/bundle/gems/rubocop-0.79.0/lib/rubocop/ast/traversal.rb:14:in `walk'
	from /usr/local/bundle/gems/rubocop-0.79.0/lib/rubocop/cop/commissioner.rb:44:in `investigate'
	from /usr/local/bundle/gems/rubocop-0.79.0/lib/rubocop/cop/team.rb:124:in `investigate'
	from /usr/local/bundle/gems/rubocop-0.79.0/lib/rubocop/cop/team.rb:112:in `offenses'
	from /usr/local/bundle/gems/rubocop-0.79.0/lib/rubocop/cop/team.rb:44:in `inspect_file'
	from /usr/src/app/lib/cc/engine/source_file.rb:14:in `inspect'
	from /usr/src/app/lib/cc/engine/rubocop.rb:35:in `block (2 levels) in run'
	from /usr/src/app/lib/cc/engine/rubocop.rb:29:in `each'
	from /usr/src/app/lib/cc/engine/rubocop.rb:29:in `block in run'
	from /usr/src/app/lib/cc/engine/rubocop.rb:28:in `chdir'
	from /usr/src/app/lib/cc/engine/rubocop.rb:28:in `run'
	from /usr/src/app/bin/codeclimate-rubocop:17:in `<main>'
```
