### ISSUE TITLE
scanning of files differs between rubocop gem and cc cli

### ISSUE THREAD

**Issue by prosanelli** [codeclimate/codeclimate-rubocop#25]
rubocop gem on the command line only scans my app folder for *.rb files.
```
rubocop -R  --format files
```

while codeclimate cli will scan image files in app/assets and files in the root of my rails apps like .travis.yml or Gemfile.

```
AllCops:
  DisabledByDefault: false
  RunRailsCops: true
  Include:
    - 'app/**/*.rb'
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'coverage/**/*'
    - 'db/**/*'
    - 'docs/**/*'
    - 'features/**/*'
    - 'lib/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'script/**/*'
    - 'spec/**/*'
    - 'test_site/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
```

```
---
engines:
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "**.coffee"
  - "**.js"
  - "**.jsx"
  - "**.css"
  - "**.scss"
exclude_paths:
- bin/**/*
- config/**/*
- db/**/*
- features/**/*
- log/**/*
- public/**/*
- script/**/*
- spec/**/*
- test_site/**/*
- tmp/**/*
- vendor/**/*
- ".codeclimate.yml"
- ".csslintrc"
- ".eslintrc"
- ".rubocop.yml"
- ".gitignore"
```

Is my codeclimate config file correct?
