### ISSUE TITLE
Run rubocop using `bundle exec rubocop`

### ISSUE THREAD

**Issue by darrenleeweber** [codeclimate/codeclimate-rubocop#72]
Our project has a custom `.rubocop.yml` file that includes cops from a published gem, e.g.:

```yaml
inherit_gem:
  dpn_cops: "config/dpn_baseline.yml"

AllCops:
  TargetRubyVersion: 2.2
```

Our project includes this gem, https://rubygems.org/gems/dpn_cops, in our `Gemfile`, e.g.
```ruby
group :development, :test do
  gem 'dpn_cops'
  # etc
end
```

So, when `rubocop` is run, it should be run within the ruby bundle to use the bundled gems.  It should be as simple as running

`bundle exec rubocop`
